select 'TODO normalize WHARGARBL' as 'Normalizing dataset by film';

update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >=     1 and movies.movieid <   500;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >=   500 and movies.movieid <  1000;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >=  1000 and movies.movieid <  1500;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >=  1500 and movies.movieid <  2000;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >=  2000 and movies.movieid <  2500;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >=  2500 and movies.movieid <  3000;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >=  3000 and movies.movieid <  3500;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >=  3500 and movies.movieid <  4000;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >=  4000 and movies.movieid <  4500;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >=  4500 and movies.movieid <  5000;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >=  5000 and movies.movieid <  5500;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >=  5500 and movies.movieid <  6000;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >=  6000 and movies.movieid <  6500;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >=  6500 and movies.movieid <  7000;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >=  7000 and movies.movieid <  7500;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >=  7500 and movies.movieid <  8000;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >=  8000 and movies.movieid <  8500;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >=  8500 and movies.movieid <  9000;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >=  9000 and movies.movieid <  9500;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >=  9500 and movies.movieid < 10000;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >= 10000 and movies.movieid < 10500;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >= 10500 and movies.movieid < 11000;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >= 11000 and movies.movieid < 11500;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >= 11500 and movies.movieid < 12000;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >= 12000 and movies.movieid < 12500;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >= 12500 and movies.movieid < 13000;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >= 13000 and movies.movieid < 13500;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >= 13500 and movies.movieid < 14000;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >= 14000 and movies.movieid < 14500;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >= 14500 and movies.movieid < 15000;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >= 15000 and movies.movieid < 15500;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >= 15500 and movies.movieid < 16000;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >= 16000 and movies.movieid < 16500;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >= 16500 and movies.movieid < 17000;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >= 17000 and movies.movieid < 17500;
update ratings join movies on ratings.movieid = movies.movieid set ratings.n_rating = ratings.rating - movies.mean where movies.movieid >= 17500 and movies.movieid < 18000;

alter table ratings add index(n_rating);
